server:
  port: 8001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/authority-manager?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      filters: stat,wall,log4j,config #\u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0C\u53BB\u6389\u540E\u76D1\u63A7\u754C\u9762SQL\u65E0\u6CD5\u8FDB\u884C\u7EDF\u8BA1\uFF0Cwall\u7528\u4E8E\u9632\u706B\u5899
      max-active: 100 #\u6700\u5927\u8FDE\u63A5\u6570
      initial-size: 1 #\u521D\u59CB\u5316\u5927\u5C0F
      max-wait: 60000 #\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u65F6\u95F4
      min-idle: 1 #\u6700\u5C0F\u8FDE\u63A5\u6570
      time-between-eviction-runs-millis: 60000 #\u95F4\u9694\u591A\u4E45\u624D\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      min-evictable-idle-time-millis: 300000 #\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4\uFF0C\u5355\u4F4D\u662F\u6BEB\u79D2
      validation-query: select 'x' #
      test-while-idle: true #
      test-on-borrow: false #
      test-on-return: false #
      pool-prepared-statements: true #
      max-open-prepared-statements: 50 #
      max-pool-prepared-statement-per-connection-size: 20 #